#ifndef SOCKETS_COMMON_H_
#define SOCKETS_COMMON_H_
typedef enum
{
    MENSAJE,
    PAQUETE,
    PCB,
    RECIBIR_PCB_ACTUALIZADO,
    INICIALIZAR_PROCESO,
    FINALIZAR_PROCESO,
    CONTEXTO,
    INSTRUCCION,
    INTERRUPCION,
    PEDIDO_INSTRUCCION
} op_cod;

#endif // SOCKETS_COMMON_H_